version: "3"

services:
  next:
    image: node
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: "yarn start"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
  
  mongo:
    image: mongo
    env_file:
      - ./.env.local
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo: